#!/bin/bash

SAVED_PWD=$PWD

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"


# NOTE: Change if you need to.
PYTHON=python3

vv () { $PYTHON -m venv venv; }
av () { source venv/bin/activate; }
pipir () { python -m pip install -r requirements.txt --quiet; }
d () { deactivate; }

reinstall () {
	folder="$1"
	if [ ! -d "$folder" ]; then
		return
	fi

	cd "$folder"
	rm -rf venv
	vv; av; pipir; d;  # create, activate, install, deactivate.
	cd ..
}

echo "[ ] Starting..."

reinstall "bandit"  &
reinstall "build"   &
reinstall "flake8"  &
reinstall "flask"   &
reinstall "mypy"    &
reinstall "pylint"  &
reinstall "twine"   &
reinstall "twisted" &
reinstall "vulture" &

wait
echo "[+] Done."
